# Generated by Django 2.1.5 on 2019-10-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order',
            name='Dropoffto',
            field=models.CharField(choices=[('Security Guard', 'Security Guard'), ('MailBox', 'MailBox'), ('Neighbour', 'Neighbour'), ('Any of the above', 'Any of the above')], max_length=255),
        ),
    ]
